/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.quanao.ui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import lombok.Setter;
import poly.quanao.dao.CategoryDAO;
import poly.quanao.dao.ProductsDAO;
import poly.quanao.dao.impl.CategoryDAOImpl;
import poly.quanao.dao.impl.OrderDetailDAOImpl;
import poly.quanao.dao.impl.ProductsDAOImpl;
import poly.quanao.entity.Category;
import poly.quanao.entity.Order;
import poly.quanao.entity.OrderDetail;
import poly.quanao.entity.Products;
import poly.quanao.util.XDialog;

/**
 *
 * @author ADMIN
 */
public final class ProductsJDialog extends javax.swing.JDialog implements ProductsController {

    /**
     * Creates new form Products
     * @param parent
     * @param modal
     */
    public ProductsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillProducts();
        fillCategories();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        tblCategory = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        tblProduct = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowIconified(java.awt.event.WindowEvent evt) {
                formWindowIconified(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Loại quần áo"
            }
        ));
        tblCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCategoryMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblCategory);

        jButton1.setText("Đóng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã quần áo", "Tên quần áo", "Giá", "Giảm giá", "Trạng thái", "Số lượng", "Màu", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductsMouseClicked(evt);
            }
        });
        tblProduct.setViewportView(tblProducts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(tblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCategoryMouseClicked
   this.fillProducts();
    }//GEN-LAST:event_tblCategoryMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowIconified(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowIconified
        // TODO add your handlingcode here:
    }//GEN-LAST:event_formWindowIconified

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
this.open();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void tblProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductsMouseClicked
         if (evt.getClickCount() == 2) {
        addProductToOrder(); // gọi thêm sản phẩm nếu double click
    }

    }//GEN-LAST:event_tblProductsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ProductsJDialog dialog = new ProductsJDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblCategory;
    private javax.swing.JScrollPane tblProduct;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
    @Setter Order order;
    CategoryDAO categoryDao = new CategoryDAOImpl();
    List<Category> categories = List.of();
    ProductsDAO ProductsDao = new ProductsDAOImpl();
    List<Products> Products = List.of();
    @Override
public void open() {
    this.setLocationRelativeTo(null);
    this.fillCategories();
    this.fillProducts();
}

@Override
public void fillCategories() {
    categories = categoryDao.findAll();
    DefaultTableModel model = (DefaultTableModel) tblCategory.getModel();
    model.setRowCount(0);
    categories.forEach(d -> model.addRow(new Object[]{d.getCategoryName()}));
    if (!categories.isEmpty()) {
        tblCategory.setRowSelectionInterval(0, 0);
    }
}

@Override
public void fillProducts() {
    int selectedRow = tblCategory.getSelectedRow();
    if (selectedRow < 0) return;

    Category category = categories.get(selectedRow);
    String categoryId = category.getCategoryId();

    this.Products = ProductsDao.findByCategoryId(categoryId); // danh sách sản phẩm

    String[] columns = {"Mã quần áo", "Tên quần áo", "Giá", "Giảm giá", "Trạng thái", "Số lượng", "Màu"};
    DefaultTableModel model = new DefaultTableModel(columns, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // không cho chỉnh sửa trực tiếp trên bảng
        }
    };

    for (Products p : this.Products) {
        String status = p.getQuantity() == 0 ? "Hết hàng" : "Còn hàng";
        Object[] row = {
            p.getProductId(),
            p.getProductName(),
            String.format("%.1f", p.getPrice()),
            String.format("%.0f%%", p.getDiscount() * 100),
            status,
            p.getQuantity(),
            p.getColor()
        };
        model.addRow(row);
    }

    tblProducts.setModel(model);
}


@Override
public void addProductToOrder() {
    int selectedRow = tblProducts.getSelectedRow(); // Đúng tên bảng
    if (selectedRow < 0) {
        XDialog.alert("Vui lòng chọn sản phẩm!");
        return;
    }

    Products product = this.Products.get(selectedRow); // dùng danh sách đúng
    int maxQuantity = product.getQuantity();

    String quantityStr = XDialog.prompt("Nhập số lượng (Tối đa: " + maxQuantity + "):");
    if (quantityStr == null || quantityStr.trim().isEmpty()) return;

    try {
        int quantity = Integer.parseInt(quantityStr.trim());

        if (quantity <= 0 || quantity > maxQuantity) {
            XDialog.alert("Số lượng phải từ 1 đến " + maxQuantity);
            return;
        }

        if (order == null || order.getOrderId() == null) {
            XDialog.alert("Vui lòng tạo đơn hàng trước khi thêm sản phẩm!");
            return;
        }

        OrderDetail detail = new OrderDetail();
        detail.setOrderId(order.getOrderId());
        detail.setProductId(product.getProductId());
        detail.setUnitPrice(product.getPrice());
        detail.setDiscount(product.getDiscount());
        detail.setQuantity(quantity);
        detail.setProductName(product.getProductName());

        new OrderDetailDAOImpl().create(detail);

        // Giảm tồn kho
        product.setQuantity(maxQuantity - quantity);
        new ProductsDAOImpl().update(product);

        fillProducts(); // cập nhật lại bảng sản phẩm

    } catch (NumberFormatException e) {
        XDialog.alert("Số lượng phải là số nguyên!");
    }
}
}
